"""插件常量。"""

from .system_prompt import (
    PROMPT_CONVERSION_SYSTEM,
    PROMPT_CONVERSION_SYSTEM_MULTI,
    TAG_CANDIDATES_FORMAT_LOCAL,
    TAG_CANDIDATES_FORMAT_ONLINE,
)

__all__ = [
    "PROMPT_CONVERSION_SYSTEM",
    "PROMPT_CONVERSION_SYSTEM_MULTI",
    "TAG_CANDIDATES_FORMAT_ONLINE",
    "TAG_CANDIDATES_FORMAT_LOCAL",
]
